config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clothing_items, :weather_backgrounds, :outfits
  
  root 'main#view'
  
  get "view(/:day)" => "main#view_day", as: 'view_day'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  #layout false

  def view
  	require 'open_weather'
		require 'json'

  	#@loc = params['loc']
  	@loc = "Miami, FL"

  	@day = (!params[:day]) ? 0 : params[:day]
  	#@day = @day.start_with?( 'day') ? @day.gsub('day', '').to_i : @day

  	@day = case @day
			when "tomorrow"
			  1
			when 0..3
				@day
			else
			  0
		end

		# get current weather by city name
		options = { units: "imperial", APPID: 'c1d8be928127b6a019f1105efb9a2fa9', cnt: 4 }
		@WeatherObj = OpenWeather::Current.city(@loc, options)
		@ForecastObj = OpenWeather::ForecastDaily.city(@loc, options)

		# set variables from returned objects
		@city = @ForecastObj['city']['name']

		@currentweather = @WeatherObj['weather'][0] 
		@currenttemp = @WeatherObj['main']['temp']	

		# daily weather
		@todaytemp = @ForecastObj['list'][0]['temp']
		@todayweather = @ForecastObj['list'][0]['weather'][0]
		@todayclouds = @ForecastObj['list'][0]['clouds']
		@forecasts = @ForecastObj['list']	

		@hash = Hash[@ForecastObj['list'].map.with_index(0) { |v,index|  
			[index,
			"weather" => [
				"min" => v['temp']['min'], 
				"max" => v['temp']['max'], 
				"id" => v['weather'][0]['id'], 
				"clouds" => v['clouds'] ]
			]
		}]
		
		#@hash = @hash.to_json

		# will remove
		@currenttemp = 96
		@currentweather['id'] = 800

		# Gather weather info to select the right outfit

		# Find weather code in db
		@cond_id = Condition.where( "owm_code = ?", @currentweather['id'])
		if @cond_id.empty? 
			# If no match, find a code prefix
			Condition.find_each do |cond|
			  if @currentweather['id'].to_s.start_with?(cond.owm_code.to_s)
			  	@cond_id = cond.id
			  end
			end
		else
			@cond_id = @cond_id.first['id']
		end

		# Find temperature range
		@temp_id = Temperature.where( "? >= degree_min AND ? <= degree_max", @currenttemp, @currenttemp)	
		if @temp_id.empty? 
			# Find hot/cold definitions if no temp range match is found
			if @currenttemp < 75
				@temp_id = Temperature.where( "degree_min IS NULL")
			else
				@temp_id = Temperature.where( "degree_max IS NULL")
			end
		end
		@temp_id = @temp_id.first['id']

		# Find an outfit based on weather conditions
		@outfit = Outfit.find_by(temperature_id: @temp_id, condition_id: @cond_id)
		if @outfit.nil? 
			@outfit = Outfit.find_by(temperature_id: @temp_id, condition_id: nil)
			if @outfit.nil? 
				@outfit = Outfit.find_by(temperature_id: nil, condition_id: @cond_id)
			end
		end

		# Find a background based on weather conditions
		@background = WeatherBackground.find_by(temperature_id: @temp_id, condition_id: @cond_id)
		if @background.nil? 
			@background = WeatherBackground.find_by(temperature_id: @temp_id, condition_id: nil)
			if @background.nil? 
				@background = WeatherBackground.find_by(temperature_id: nil, condition_id: @cond_id)
			end
		end
  end

  def view_day

  	require 'open_weather'

  	@loc = "Miami, FL"

  	# get current weather by city name
		options = { units: "imperial", APPID: 'c1d8be928127b6a019f1105efb9a2fa9', cnt: 4 }
		@WeatherObj = OpenWeather::Current.city(@loc, options)
		@ForecastObj = OpenWeather::ForecastDaily.city(@loc, options)

		# set variables from returned objects
		@city = @ForecastObj['city']['name']

  	@day = (!params[:day]) ? 0 : params[:day].to_i

  	@day = case @day
			when 0..3
				@day
			else
			  0
		end

		# get current weather by city name
		options = { units: "imperial", APPID: 'c1d8be928127b6a019f1105efb9a2fa9', cnt: 4 }
		@WeatherObj = OpenWeather::Current.city(@loc, options)
		@ForecastObj = OpenWeather::ForecastDaily.city(@loc, options)

		# set variables from returned objects
		@city = @ForecastObj['city']['name']

		# daily weather
		@todaytemp = @ForecastObj['list'][@day]['temp']
		@todayweather = @ForecastObj['list'][@day]['weather'][0]
		@todayclouds = @ForecastObj['list'][@day]['clouds']
		@forecasts = @ForecastObj['list']	

		# will remove
		@todaytemp['day'] = 96
		@todayweather['id'] = 500
		@currentweather = @todayweather

		# Gather weather info to select the right outfit

		# Find weather code in db
		@cond_id = Condition.where( "owm_code = ?", @todayweather['id'])
		if @cond_id.empty? 
			# If no match, find a code prefix
			Condition.find_each do |cond|
			  if @todayweather['id'].to_s.start_with?(cond.owm_code.to_s)
			  	@cond_id = cond.id
			  end
			end
		else
			@cond_id = @cond_id.first['id']
		end

		# Find temperature range
		@temp_id = Temperature.where( "? >= degree_min AND ? <= degree_max", @todaytemp['day'], @todaytemp['day'])	
		if @temp_id.empty? 
			# Find hot/cold definitions if no temp range match is found
			if @todaytemp['day'] < 75
				@temp_id = Temperature.where( "degree_min IS NULL")
			else
				@temp_id = Temperature.where( "degree_max IS NULL")
			end
		end
		@temp_id = @temp_id.first['id']

		# Find an outfit based on weather conditions
		@outfit = Outfit.find_by(temperature_id: @temp_id, condition_id: @cond_id)
		if @outfit.nil? 
			@outfit = Outfit.find_by(temperature_id: @temp_id, condition_id: nil)
			if @outfit.nil? 
				@outfit = Outfit.find_by(temperature_id: nil, condition_id: @cond_id)
			end
		end

		# Find a background based on weather conditions
		@background = WeatherBackground.find_by(temperature_id: @temp_id, condition_id: @cond_id)
		if @background.nil? 
			@background = WeatherBackground.find_by(temperature_id: @temp_id, condition_id: nil)
			if @background.nil? 
				@background = WeatherBackground.find_by(temperature_id: nil, condition_id: @cond_id)
			end
		end

		respond_to do |format|
      format.js {}
    end

  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_footer.html.erb
<footer>
	<div class="row expanded">
		<div class="medium-6 column">
			<!--<ul class="menu">
				<li><a href="#">Legal</a></li>
				<li><a href="#">Partner</a></li>
				<li><a href="#">Explore</a></li>
			</ul>-->
		</div>
		<div class="medium-6 column"><br/>
			<ul class="menu align-right">
				<!--<li class="menu-text">Copyright © 2016 Tempdress</li>-->
			</ul>
		</div>
	</div>
</footer>

app/views/main/_items.html.erb
<div class="row" data-equalizer>

	<% for i in 1..2 %>
	  <div class="large-4 medium-6 column clothes" data-equalizer-watch>
			<% @clothes = @outfit.clothing_items.where("column_num = ?", i).order("outfit_item_details.position ASC") %>
			<% @clothes.each do |c| %>
			  <a class="<%= c.size %> clothing-item" href="<%= c.link %>" target="_blank">
			  	<%= image_tag c.image.url(:large) %>
			 	</a>
			<% end %>
		</div>
	<% end %>

	<div id="outfit_description" class="large-4 medium-6 column" data-equalizer-watch>
		<main class="description_wrapper">
			<h2><%= @outfit.name %></h2>
			<div id="content">
				<strong>#<%= @outfit.id %>.</strong> 
				<%= @outfit.description %>
			</div>
		</main>
	</div>

</div>

app/views/main/_navigation.html.erb
<!-- app/views/main/_navigation.html.erb -->

<nav class="top-bar" data-topbar role="navigation">
  <div class="row">
    <div class="small-12 column">
		  <ul class="title-area">
		    <li class="name">
		      <h1><a href="/">Tempdress</a></h1>
		    </li>

		    <li class="toggle-topbar">
		      <a href="#"><span>Menu</span></a>
		    </li>
		  </ul>
		  <ul class="date">
		  	<li><%= Time.now.strftime("%A, %B %d") %></li>
		  </ul>
		  <hr/>
		</div>
	</div>
</nav>

app/views/main/_sidebar.html.erb
<div id="weather">
	<%= render 'weather' %>
</div>
<div id="days">
		
	<% (0..3).each do |i| %>
		<% @label = case i
				when 0
					"Today"
				when 1
					"Tomorrow"
				else
				  (Time.now + i.days).strftime("%A")
			end
		%>
		<p class="day-control">
			<%= link_to view_day_path(:day => i), :remote => true, data: {type: "script"} do %>
			  <%= @label %><span></span>
			<% end %>
		</p>   
	<% end %>
</div>

app/views/main/_weather.html.erb
<div id="conditions">
	<div id="icon">
		<i class="wi wi-owm-<%= @currentweather['id'] %>"></i>
	</div>
	<div id="clouds"><%= @todayclouds %><sup>%</sup></div>
</div>
<div id="temperatures">
	<div id="high"><%= @todaytemp['max'].round %>&deg;</div>
	<div id="low"><%= @todaytemp['min'].round %>&deg;</div>
</div>

app/views/main/view.html.erb
<div class="row" data-equalizer>

	<% for i in 1..2 %>
	  <div class="medium-4 column clothes" data-equalizer-watch>
			<% @clothes = @outfit.clothing_items.where("column_num = ?", i).order("outfit_item_details.position ASC") %>
			<% @clothes.each do |c| %>
			  <a class="<%= c.size %> clothing-item" href="<%= c.link %>" target="_blank">
			  	<%= image_tag c.image.url(:large) %>
			 	</a>
			<% end %>
		</div>
	<% end %>

	<div id="outfit_description" class="medium-4 column" data-equalizer-watch>
		<main class="description_wrapper">
			<h2><%= @outfit.name %></h2>
			<div id="content">
				<strong>#<%= @outfit.id %>.</strong> 
				<%= @outfit.description %>
			</div>
		</main>
	</div>

</div>

app/views/main/view_day.js.erb
 $("body").css("background-image", "url(<%= escape_javascript(@background.image.url)%>)"); 
 $("#outfit_info").html("<%= escape_javascript(render partial: 'items') %>"); 
 $("#weather").html("<%= escape_javascript(render partial: 'weather') %>"); 
 $('.day-control a').eq("<%=@day%>").addClass("selected");