config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clothing_items, :weather_backgrounds, :outfits
  
  root 'main#view'
  
  get "view(/:day)" => "main#view_day", as: 'view_day'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
	
	belongs_to :condition
	belongs_to :temperature

	has_many :outfit_item_details
  has_many :clothing_items, -> { select(
  	'clothing_items.*, 
  	outfit_item_details.position as position,
  	outfit_item_details.column_num as column_num,
  	outfit_item_details.tile_size as size
  	'
  ) }, :through => :outfit_item_details

	accepts_nested_attributes_for :outfit_item_details, :allow_destroy => true

	scope :published, lambda { where(:visible => true)}
	scope :unpublished, lambda { where(:visible => false)}
	scope :day, lambda { where(:day => true)}
	scope :evening, lambda { where(:day => false)}

end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController

  layout "backend"

  before_action :set_outfit, only: [:show, :edit, :update, :destroy]

  # GET /outfits
  def index
    @outfits = Outfit.all
  end

  # GET /outfits/1
  def show
  end

  # GET /outfits/new
  def new
    @outfit = Outfit.new
  end

  # GET /outfits/1/edit
  def edit
  end

  # POST /outfits
  def create
    @outfit = Outfit.new(outfit_params)

    if @outfit.save
      redirect_to @outfit, notice: 'Outfit was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /outfits/1
  def update
    if @outfit.update(outfit_params)
      redirect_to @outfit, notice: 'Outfit was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /outfits/1
  def destroy
    @outfit.destroy
    redirect_to outfits_url, notice: 'Outfit was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outfit
      @outfit = Outfit.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def outfit_params
      params.require(:outfit).permit(:condition_id, :temperature_id, :name, :description, :day, :visible, {:clothing_item_ids => []})
    end
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_form.html.erb
<%= simple_form_for(@outfit) do |f| %>
  <%= f.error_notification %>
  <% @conditions = Condition.all %>
  <% @temps = Temperature.all %>
  <% @items = ClothingItem.all %>

  <div class="form-inputs">
  	<%= f.input :name %><br/>
    <%= f.input :description %><br/>

    <% @clothes = @outfit.clothing_items %>

  	<%= f.collection_check_boxes(:clothing_item_ids, @items, :id, :name, allow_destroy: true) do |b, c| %>
      <% item = @items.detect{|img| img.id == b.value } %>
      <div class="clothing-item-choice">
				<%= image_tag(item.image.url(:small)) %><br/>
				<%= b.label { b.check_box + b.text } %>
			</div>
    <% end %>

    <br/>

    <% @conditions.each do |c| %>
      <%= c.name %>: <%= f.radio_button :condition_id, c.id %> &nbsp;
    <% end %>

    <br/>

    <% @temps.each do |c| %>
      <%= c.name %>: <%= f.radio_button :temperature_id, c.id %> &nbsp;
    <% end %>

    <br/>

    Daytime look? <%= f.check_box(:day) %><br/>
    
    Publish? <%= f.check_box(:visible) %><br/>
      
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/outfits/delete.html.erb
<h1>Outfits#delete</h1>
<p>Find me in app/views/outfits/delete.html.erb</p>

app/views/outfits/edit.html.erb
<h1>Editing Outfit</h1>

<%= render 'form' %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Outfits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Condition</th>
      <th>Temperature</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @outfits.each do |outfit| %>
      <tr>
        <td><%= outfit.name %></td>
        <td><%= outfit.condition.name %></td>
        <td><%= outfit.temperature.name %></td>
        <td><%= outfit.visible ? 'Published' : 'Draft' %></td>
        <td><%= link_to 'Show', outfit %></td>
        <td><%= link_to 'Edit', edit_outfit_path(outfit) %></td>
        <td><%= link_to 'Destroy', outfit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Outfit', new_outfit_path %>

app/views/outfits/new.html.erb
<h1>New Outfit</h1>

<%= render 'form' %>

<%= link_to 'Back', outfits_path %>

app/views/outfits/show.html.erb
<p id="notice"><%= notice %></p>

<div class="outfits show">
  <h2>Show Outfit</h2>

  <table summary="Outfit detail view">
    <tr>
      <th>Name</th>
      <td><%= @outfit.name %></td>
    </tr>
    <tr>
      <th>Description</th>
      <td><%= @outfit.description %></td>
    </tr>
    <tr>
      <th>Condition</th>
      <td><%= @outfit.condition.name %></td>
    </tr>
    <tr>
      <th>Temperature</th>
      <td><%= @outfit.temperature.name %></td>
    </tr>
    <tr>
      <th>Day or Evening</th>
      <td><%= @outfit.day ? 'Day' : 'Evening' %></td>
    </tr>
     <tr>
      <th>Clothing Items</th>
      <td>
        <% @clothes = @outfit.clothing_items %>
        <ul>
        <% @clothes.each do |c| %>
          <li><%= c.name %></li>
        <% end %>
        </ul>
      </td>
    </tr>
    <tr>
      <th>Published</th>
      <td><%= @outfit.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @outfit.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @outfit.updated_at %></td>
    </tr>
  </table>

</div>

<%= link_to 'Edit', edit_outfit_path(@outfit) %> |
<%= link_to 'Back', outfits_path %>