config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clothing_items, :weather_backgrounds, :outfits
  
  root 'main#view'
  
  get "view(/:day)" => "main#view_day", as: 'view_day'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/weather_background.rb
class WeatherBackground < ActiveRecord::Base
	belongs_to :condition
	belongs_to :temperature
	has_attached_file :image, styles: { small: "150x150", med: "375x375", large: "1024x1024" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/weather_backgrounds_controller.rb
class WeatherBackgroundsController < ApplicationController

  layout false

  before_action :set_weather_background, only: [:show, :edit, :update, :destroy]

  # GET /weather_backgrounds
  def index
    @weather_backgrounds = WeatherBackground.all
  end

  # GET /weather_backgrounds/1
  def show
  end

  # GET /weather_backgrounds/new
  def new
    @weather_background = WeatherBackground.new
  end

  # GET /weather_backgrounds/1/edit
  def edit
  end

  # POST /weather_backgrounds
  def create
    @weather_background = WeatherBackground.new(weather_background_params)

    if @weather_background.save
      redirect_to @weather_background, notice: 'Weather background was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /weather_backgrounds/1
  def update
    if @weather_background.update(weather_background_params)
      redirect_to @weather_background, notice: 'Weather background was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /weather_backgrounds/1
  def destroy
    @weather_background.destroy
    redirect_to weather_backgrounds_url, notice: 'Weather background was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather_background
      @weather_background = WeatherBackground.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def weather_background_params
      params.require(:weather_background).permit(:name, :condition_id, :temperature_id, :image)
    end
end

app/helpers/weather_backgrounds_helper.rb
module WeatherBackgroundsHelper
end

app/views/weather_backgrounds/_form.html.erb
<%= simple_form_for(@weather_background, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>
  <% @conditions = Condition.all %>
  <% @temps = Temperature.all %>

  <div class="form-inputs">
    <%= f.input :name %><br/>
    
    <% @conditions.each do |c| %>
      <%= c.name %>: <%= f.radio_button :condition_id, c.id %> &nbsp;
    <% end %>

    <br/>

    <% @temps.each do |c| %>
      <%= c.name %>: <%= f.radio_button :temperature_id, c.id %> &nbsp;
    <% end %>
    
    <br/>
   
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/weather_backgrounds/edit.html.erb
<h1>Editing Weather Background</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather_background %> |
<%= link_to 'Back', weather_backgrounds_path %>

app/views/weather_backgrounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Weather Backgrounds</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Condition</th>
      <th>Temperature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weather_backgrounds.each do |weather_background| %>
      <tr>
        <td><%= image_tag(weather_background.image.url(:small)) %></td>
        <td><%= weather_background.name %></td>
        <td><%= weather_background.condition.present? ? weather_background.condition.name : "Any" %></td>
        <td><%= weather_background.temperature.present? ? weather_background.temperature.name : "Any" %></td>
        <td><%= link_to 'Show', weather_background %></td>
        <td><%= link_to 'Edit', edit_weather_background_path(weather_background) %></td>
        <td><%= link_to 'Destroy', weather_background, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather background', new_weather_background_path %>

app/views/weather_backgrounds/new.html.erb
<h1>New Weather Background</h1>

<%= render 'form' %>

<%= link_to 'Back', weather_backgrounds_path %>

app/views/weather_backgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @weather_background.name %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @weather_background.condition.present? ? @weather_background.condition.name : "Any" %>
</p>

<p>
  <strong>Temperature:</strong>
	<%= @weather_background.temperature.present? ? @weather_background.temperature.name : "Any" %>
</p>

<p>
  <strong>Image:</strong>
	<%= link_to image_tag(@weather_background.image.url(:med)), @weather_background.image.url %>
</p>

<%= link_to 'Edit', edit_weather_background_path(@weather_background) %> |
<%= link_to 'Back', weather_backgrounds_path %>