config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :clothing_items, :weather_backgrounds, :outfits
  
  root 'main#view'
  
  get "view(/:day)" => "main#view_day", as: 'view_day'

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/clothing_item.rb
class ClothingItem < ActiveRecord::Base
	has_many :outfit_item_details
  has_many :outfits, :through => :outfit_item_details
	has_attached_file :image, styles: { small: "150x150", med: "375x375", large: "1024x1024" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/clothing_items_controller.rb
class ClothingItemsController < ApplicationController

  layout "backend"

  before_action :set_clothing_item, only: [:show, :edit, :update, :destroy]

  # GET /clothing_items
  def index
    @clothing_items = ClothingItem.all
  end

  # GET /clothing_items/1
  def show
  end

  # GET /clothing_items/new
  def new
    @clothing_item = ClothingItem.new
  end

  # GET /clothing_items/1/edit
  def edit
  end

  # POST /clothing_items
  def create
    @clothing_item = ClothingItem.new(clothing_item_params)

    if @clothing_item.save
      redirect_to @clothing_item, notice: 'Clothing item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /clothing_items/1
  def update
    if @clothing_item.update(clothing_item_params)
      redirect_to @clothing_item, notice: 'Clothing item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /clothing_items/1
  def destroy
    @clothing_item.destroy
    redirect_to clothing_items_url, notice: 'Clothing item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clothing_item
      @clothing_item = ClothingItem.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def clothing_item_params
      params.require(:clothing_item).permit(:name, :link, :price, :image)
    end
end

app/helpers/clothing_item_helper.rb
module ClothingItemHelper
end

app/helpers/clothing_items_helper.rb
module ClothingItemsHelper
end

app/views/clothing_items/_form.html.erb
<%= simple_form_for(@clothing_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name %><br/>
  	<%= f.input :link %><br/>
  	<%= f.input :price %><br/>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clothing_items/delete.html.erb
<h1>ClothingItem#delete</h1>
<p>Find me in app/views/clothing_item/delete.html.erb</p>

app/views/clothing_items/edit.html.erb
<h1>Editing Clothing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @clothing_item %> |
<%= link_to 'Back', clothing_items_path %>

app/views/clothing_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clothing Items</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clothing_items.each do |clothing_item| %>
      <tr>
        <td><%= image_tag(clothing_item.image.url(:small)) %></td>
        <td><%= clothing_item.name %></td>
        <td><%= number_to_currency(clothing_item.price) %></td>
        <td><%= link_to 'Show', clothing_item %></td>
        <td><%= link_to 'Edit', edit_clothing_item_path(clothing_item) %></td>
        <td><%= link_to 'Destroy', clothing_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clothing item', new_clothing_item_path %>

app/views/clothing_items/new.html.erb
<h1>New Clothing Item</h1>

<%= render 'form' %>

<%= link_to 'Back', clothing_items_path %>

app/views/clothing_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_clothing_item_path(@clothing_item) %> |
<%= link_to 'Back', clothing_items_path %>